version: 2

sources:
    - name: citibike_project
      description: Snowflake S3 Lab Citibike data 
      database: source_db
      schema: raw
      tables:
          - name: weather
          - name: citibike_csv_trips
